### ISSUE TITLE
Image upload for screenshot.png

### ISSUE THREAD

**Issue by jdsteinbach** [Automattic/underscores.me#15]
Would be great to add an image upload field to the Advanced Options section so that users have the option to include a screenshot image when creating a new theme.

**Comment by laurianops** [comment]
@obenland e @jdsteinbach, i am beginner to wordpress, do you know how i add the screenshot in wordpress panel? theme apparence ?

**Comment by obenland** [comment]
It has to be added to the theme folder itself. 
See https://developer.wordpress.org/themes/release/required-theme-files/
