### ISSUE TITLE
Add in Genericons as sub module

### ISSUE THREAD

**Issue by karmatosed** [Automattic/underscores.me#29]
Relating to: https://github.com/Automattic/_s/pull/567 over at _s, this is an issue to look at adding Genericons as an option when downloading _s.

**Comment by davidakennedy** [comment]
Thanks @karmatosed!

With the deprecation of Genericons, and the newer social menu in Jetpack, this isn't something we're likely to do.

We may explore ways to add SVGs though. But I'm going to close this out for now.
