### ISSUE TITLE
theme fails to validate on themecheck.org

### ISSUE THREAD

**Issue by senlin** [Automattic/underscores.me#33]
Although the critical alerts have nothing to do with the theme, there are quite a few warnings on deprecated code: http://themecheck.org/score/wordpress_theme_underscores_me.html

**Comment by davidakennedy** [comment]
Thanks for the issue @senlin!

Some of that has to do with the bundled plugin for the generator, and the rest has to do with the fact this site's theme is from an older version of Underscores. At some point when we redesign, we'll address the old code. For now, I'm going to close this.

**Comment by senlin** [comment]
wow, ain't that a speedy follow up!
