### ISSUE TITLE
Theme Name _s Getting Replaced When It Should Not

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/underscores.me#39]
See: https://github.com/Automattic/_s/issues/808

Specifically: https://cloud.githubusercontent.com/assets/1828768/9420739/61d85384-4869-11e5-80f0-d709fc4e6b8a.jpg

Line 6 of `skip-link-focus-fix.js` should not get replaced.

**Comment by fostertime** [comment]
Since it looks like a very limited case. Maybe just replace the URL with a git.io URL? Just a thought.

http://git.io/vWdr2
