### ISSUE TITLE
Primary Menu button leaves menu stuck in toggled state on window resize

### ISSUE THREAD

**Issue by iCaspar** [Automattic/underscores.me#41]
When you are looking at the main menu in a narrow browser window such that the "Primary Menu" button is visible, then click on the menu to toggle the hidden list below. Then, if you resize the browser window with the menu open, the css causes the button not to display, so the user can't click to close the open menu. Screenshots on a recent project based on underscores attached.
![primary menu button triggered](https://cloud.githubusercontent.com/assets/7462998/10999117/4489f770-8468-11e5-91f0-e92fe85fd2ef.png)
![open menu hanging with no button for user to close](https://cloud.githubusercontent.com/assets/7462998/10999118/448ecbec-8468-11e5-9e3e-c14bc911986b.png)

**Comment by sarahmonster** [comment]
Hi there,

This repository is for the website for underscores.me. For issues related to _s itself, you'd want to file them in that repo: https://github.com/Automattic/_s

I did a quick test of _s to confirm this behaviour, but it isn't happening there. I suspect this means there's some code in your theme that's causing this behaviour. 

For theme support and development help, please head over to https://wordpress.org/support/forum/themes-and-templates where the community will be happy to help out. :)

Have a lovely day!
