### ISSUE TITLE
improper use of `query_post()`

### ISSUE THREAD

**Issue by mikeritter** [Automattic/underscores.me#43]
I'm noticing the casual use of `query_posts()` in the templates.

Interestingly, https://codex.wordpress.org/Function_Reference/query_posts clearly states this should NOT be used in themes and plugins.

Please clear this up.

Is the Automattic team pushing us int this direction?

Is the linked article inaccurate in stating the query should be reset after called?

**Comment by jacklenox** [comment]
@mikeritter Where are you noticing these? I see no instances of `query_posts()` in either [_s itself](https://github.com/Automattic/_s/search?utf8=%E2%9C%93&q=query_posts) or [this repo](https://github.com/Automattic/underscores.me/search?utf8=%E2%9C%93&q=query_posts), the theme for the [_s website](http://underscores.me/).

**Comment by mikeritter** [comment]
My error. Undocumented change on my part.
