### ISSUE TITLE
Lower the version number to 0.1.0

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/underscores.me#44]
The first step everybody does is probably to lower the version of the downloaded theme to 0.1.0

I think this task could be done when you download a new theme from underscores.me, in the case you want to keep to version on the repository to 1.0.0. Otherwise, we could simply lower the version to 0.1.0.

What are your opinions?

Same things should by applied to components.underscores.me / theme-components repository.

**Comment by davidakennedy** [comment]
Thanks for the issue @benoitchantre! I don't think this is a big deal. Theme authors can easily change it to whatever they'd like to after generating a theme.
