### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by dadmor** [Automattic/underscores.me#45]
On underscores.me landing page, with code (inside html) I found that structure:

```
<div id="main"> 
        <div id="primary" class="site-content">...</div>
</div>
```

If I'll download generated theme zip - code are reciprocal:

```
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">...</main>
    </div>
</div>
```

and don't have `<section>` selector.

I'll could create Pull request for this.

**Comment by davidakennedy** [comment]
Thanks for the issue @dadmor! The site is based on an older version of Underscores, so there will be some differences. We don't intend to keep it in line with the current Underscores code, and would only adjust it when we decided to do a redesign.
