### ISSUE TITLE
Profile missing in contributors list

### ISSUE THREAD

**Issue by ernilambar** [Automattic/underscores.me#46]
I am listed as contributor in repo https://github.com/Automattic/_s/graphs/contributors but my profile is not displaying in http://underscores.me contributors list.

**Comment by davidakennedy** [comment]
Hi @ernilambar – thanks for your contributions. There's a line about this in the _s [guidelines for contributing](https://github.com/Automattic/_s/blob/master/CONTRIBUTING.md).

> Want to have your avatar listed as one of the _s contributors here? Just make sure you have an email address added to both GitHub and your local Git installation.

I believe that may be what you need to do to make it work. Hope this helps!

**Comment by ernilambar** [comment]
I dont think that is the case. My profile was there for few months and then it disappeared.

**Comment by davidakennedy** [comment]
Okay, thanks @ernilambar for letting me know. Looks like this is likely related to #22. So I try to get a fix there soon.
