### ISSUE TITLE
Background image is on home page but not my woocomerce side

### ISSUE THREAD

**Issue by troubleme** [Automattic/underscores.me#50]
I'm new to the forum. Long story short, I got ripped off by a webdesign company and now I'm trying to put my site together from what I have saved/backed up, I imported it to a godaddy wordpress hosting and I think I have it up and running but I seem to have some images missing in some pages but not in others (my home page). Certain pages (Home page) my background image shows but when I click a product and it takes me to a product page I do not have the background image like I use to. I'm not a webdesigner/builder but I manage to learn many things along the way. Can someone please help?

**Comment by grappler** [comment]
This is not a support forum forum. You should be able to ask your question here: https://wordpress.org/support/

If images are missing then you will need to reupload them using the file name to hosting via FTP, or reupload them again via the Media page and correct the images in the content and settings.
