### ISSUE TITLE
Sass and Grid system

### ISSUE THREAD

**Issue by chmchm** [Automattic/underscores.me#61]
Hey all!
Is there a reason the bootstrap grid is not part of the sass files? I was using the regular bootstrap then decided I wanted to use the sass for variables and poof! The grid was gone. Did I miss something?
Thanks in advance,
Christina

**Comment by grappler** [comment]
@chmchm This repo is for the website and theme generator and not for the theme. The theme repo can be found here: https://github.com/automattic/_s

> Is there a reason the bootstrap grid is not part of the sass files?

Bootstrap has never been included in `_s`. I don't think any grid has been included for that matter.

As GitHub is used for the development of the tools and your question is more in line of support you are probably better off on the wordpress.org forums, the WordPress Stack Exchange (http://wordpress.stackexchange.com), or IRC (#wordpress on Freenode).

**Comment by davidakennedy** [comment]
Hi @chmchm! Thanks for the issue, but as pointed out, please head to other places to get support for further development using _s. Good luck!
