### ISSUE TITLE
Adding custom pages to my underscores theme

### ISSUE THREAD

**Issue by jordan-miguel** [Automattic/underscores.me#64]
Hi guys, relatively new wordpress developer here.

How can I add my own unique pages to my site? Is the same as I normally would do, through Custom Page Templates?

**Comment by grappler** [comment]
Hi Jordan

This GitHub repo is being used to track the issues and features with the `_s` theme generator.

The best place for support is the [WordPress support forums](https://wordpress.org/support/forum/wp-advanced/) or [WordPress Stackexchange](wordpress.stackexchange.com).

Or you could checkout the Theme Developers Handbook which explains everything about page templates. https://developer.wordpress.org/themes/template-files-section/page-template-files/

`_s` is a normal theme so page templates will work like with any other theme.

**Comment by gabriele-carbonai** [comment]
I think have an issue about page template, because you need to naming file like this: page_custom.php and in wordpress documentation is page-custom.php
bytheway, I have the same issue with the category, I try name the file with both symbols but is not show

**Comment by texxs** [comment]
Are you kidding? Those are horrible places to get help on using the Underscores theme.  and te reply did nothing to address the main question in hand, not even a link to what the codex, which is only a little helpful in this case, says on this subject (https://codex.wordpress.org/Pages) is provided. 

As for help on using the underscores theme, try this:
https://torquemag.io/2017/08/beginners-guide-to-creating-a-theme-underscores/
