### ISSUE TITLE
WooCommerce Theme Support

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/underscores.me#65]
The theme/inc/woocommerce.php file could use some compatibility updates for WC 3.3+

See: https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes

Namely should remove `loop_shop_columns` and `loop_shop_per_page` filters and use new theme support options for those.

**Comment by jrfnl** [comment]
Wrong repo. I believe you want https://github.com/Automattic/_s/ and probably in particular https://github.com/Automattic/_s/issues/1257

**Comment by WPprodigy** [comment]
Woops, thanks.
