### ISSUE TITLE
Readme.txt file of theme has been giving wrong date and version in the changelog.

### ISSUE THREAD

**Issue by girishpanchal07** [Automattic/underscores.me#68]
I have created the new theme using this command `wp scaffold _s test-theme --theme_name="Test Theme" --author="Me"` after installing the theme I found wrong changelog detail in the readme.txt also found the wrong versioning as compared to stable tag on the file.

The changelog date should the same date when theme installed and they changelog tag should same as the stable tag.

Check the below screenshot.

![screenshot-jun-26-18](https://user-images.githubusercontent.com/18365991/41907339-26576d80-795e-11e8-93e4-a06f42049469.png)
.

**Comment by grappler** [comment]
For the version inconsistency it would be best to create an issue and if you are up for it an pull request to https://github.com/Automattic/_s

I suppose replacing "May 12 2015" with the date the theme was generated would be possible.

**Comment by girishpanchal07** [comment]
@grappler 

I have sent pull request after updating changelog stable tag and date replaced with 2015 to 2018.
Also, I have updated **tested up to** WordPress version in readme.txt.

https://github.com/Automattic/_s/pull/1300
