### ISSUE TITLE
Custom header images not working in version wordpress 5.0.3 

### ISSUE THREAD

**Issue by kiwiheretic** [Automattic/underscores.me#70]
On a freshly installed wordpress version the custom header image is not displaying at all.

**Comment by crunnells** [comment]
Hey @kiwiheretic this repo is for issues specific to the underscores.me web site. Please report issues with the `_s` theme to the [repo here](https://github.com/Automattic/_s/).

In response to your issue, without modifications `_s` doesn't have the code to display the header image in the template, so you'll need to add `the_header_image_tag()` to the appropriate template file (eg: usually `header.php`).
